/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Dialog: typeof import('./src/components/component/dialog.vue')['default']
    EchartBody: typeof import('./src/components/component/EchartBody.vue')['default']
    Header: typeof import('./src/components/component/header.vue')['default']
    Preview: typeof import('./src/components/component/imageViewer/Preview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/component/searchBar.vue')['default']
    SideMenu: typeof import('./src/components/component/sideMenu.vue')['default']
    TopMenu: typeof import('./src/components/component/topMenu.vue')['default']
    VideoWaterfall: typeof import('./src/components/component/videoWaterfall.vue')['default']
    VpTooltip: typeof import('./src/components/component/vpTooltip.vue')['default']
    WaterFall: typeof import('./src/components/component/waterFall/waterFall.vue')['default']
    WordCloud: typeof import('./src/components/component/wordCloud.vue')['default']
  }
}
